# Generated by Django 6.0.2 on 2026-02-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=100)),
                ('feature', models.CharField(max_length=500)),
                ('image', models.URLField()),
            ],
        ),
    ]
