# Generated by Django 6.0.2 on 2026-02-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salon',
            old_name='salon_name',
            new_name='name',
        ),
    ]
