# Generated by Django 6.0.2 on 2026-02-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_salon_name_salon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
