# Generated by Django 6.0.2 on 2026-02-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_salon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.URLField(max_length=10000),
        ),
    ]
