# Generated by Django 6.0.2 on 2026-02-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='eamil',
            new_name='email',
        ),
    ]
